version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/valegro-acebook
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: Scripts/application-stop.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: Scripts/after-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: Scripts/application-start.sh
      timeout: 300
      runas: ec2-user